// Packs the sound folders into scripts the game can load from file:// (see js/audio/assets.js).
//   node tools/audio/pack.js            packs every folder in assets/audio-src
//   node tools/audio/pack.js court      packs one folder
// Each source folder holds .wav / .ogg / .mp3 / .m4a files and a LICENSES.json:
//   { "dribble_01.ogg": { "license": "CC0", "source": "https://...", "author": "..." }, ... }
// A file with no license entry is refused, so nothing unlicensed ever ships.
// Output: assets/audio/<folder>/pack.js and assets/audio/manifest.js.
const fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..', '..');
const SRC = path.join(root, 'assets/audio-src'), OUT = path.join(root, 'assets/audio');
const FOLDERS = ['court', 'crowd', 'chants', 'chatter', 'arena', 'commentary'];
const MIME = { '.wav': 'audio/wav', '.ogg': 'audio/ogg', '.mp3': 'audio/mpeg', '.m4a': 'audio/mp4' };
const FREE = /^(CC0|CC-BY(-\d\.\d)?|CC BY( \d\.\d)?|Public Domain|MIT|Apache-2\.0|Original|Pixabay|OGA-BY)/i;

function packFolder(folder, srcDir, outDir) {
  const dir = path.join(srcDir, folder);
  if (!fs.existsSync(dir)) return null;
  const licFile = path.join(dir, 'LICENSES.json');
  const lic = fs.existsSync(licFile) ? JSON.parse(fs.readFileSync(licFile, 'utf8')) : {};
  const files = fs.readdirSync(dir).filter(f => MIME[path.extname(f).toLowerCase()]).sort();
  const lines = [], problems = [];
  let bytes = 0;
  for (const f of files) {
    const m = lic[f];
    if (!m || !m.license) { problems.push(`${folder}/${f}: no license entry in LICENSES.json, skipped`); continue; }
    if (!FREE.test(m.license)) { problems.push(`${folder}/${f}: license "${m.license}" is not on the free list, skipped`); continue; }
    const data = fs.readFileSync(path.join(dir, f));
    bytes += data.length;
    const id = `${folder}/${path.basename(f, path.extname(f))}`;
    const meta = { license: m.license, source: m.source || '', author: m.author || '' };
    lines.push(`R(${JSON.stringify(id)},"data:${MIME[path.extname(f).toLowerCase()]};base64,${data.toString('base64')}",${JSON.stringify(meta)});`);
  }
  if (!lines.length) return { folder, count: 0, bytes: 0, problems };
  fs.mkdirSync(path.join(outDir, folder), { recursive: true });
  const body = `/* generated by tools/audio/pack.js from assets/audio-src/${folder}; do not edit */\n(function(){var R=window.PBC.AudioAssets.register;\n${lines.join('\n')}\n})();\n`;
  fs.writeFileSync(path.join(outDir, folder, 'pack.js'), body);
  return { folder, count: lines.length, bytes, problems, file: `assets/audio/${folder}/pack.js` };
}

function run(folders, srcDir, outDir) {
  const res = folders.map(f => packFolder(f, srcDir, outDir)).filter(Boolean);
  const packs = res.filter(r => r.count).map(r => ({ folder: r.folder, file: r.file, count: r.count }));
  // keep packs of folders not rebuilt this run
  const manFile = path.join(outDir, 'manifest.js');
  let old = [];
  if (fs.existsSync(manFile)) { const m = /manifest = (\{[\s\S]*\});/.exec(fs.readFileSync(manFile, 'utf8')); if (m) old = JSON.parse(m[1]).packs || []; }
  const merged = old.filter(p => !folders.includes(p.folder)).concat(packs).sort((a, b) => a.folder.localeCompare(b.folder));
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(manFile, `/* generated by tools/audio/pack.js; do not edit */\nwindow.PBC = window.PBC || {};\nwindow.PBC.AudioAssets = window.PBC.AudioAssets || {};\nwindow.PBC.AudioAssets.manifest = ${JSON.stringify({ packs: merged }, null, 1)};\n`);
  return res;
}

if (require.main === module) {
  const want = process.argv[2] ? [process.argv[2]] : FOLDERS;
  for (const r of run(want, SRC, OUT)) {
    console.log(`${r.folder}: ${r.count} sound(s), ${(r.bytes / 1024).toFixed(1)} KB`);
    for (const p of r.problems) console.log('  ! ' + p);
  }
}
module.exports = { run, packFolder, FOLDERS };
