#!/usr/bin/env node
// Sound packs: turns assets/audio/<folder>/ into js/audio/packs/<folder>.js (the files base64-encoded) so the game can
// load them from a page opened as a local file (file://, where fetch is blocked), and rewrites js/audio/packs/index.js
// (the list of packs that exist).
//
//   node tools/audio/pack.js <folder> [<folder> ...]     e.g.  node tools/audio/pack.js test
//   node tools/audio/pack.js --all
//
// Every audio file must have a row in its folder's LICENSES.md table naming the file, its source, its author and its
// license, and the license must be one the project can ship (CC0 / public domain, CC BY with the credit written in
// the row, the Pixabay Content License, or made by this project). A file with no row, or with another license, stops
// the packer: no sound goes into the game before its license has been checked (the audio gauntlet's ground rule 2).
// One exception: sounds made on ElevenLabs' free plan are allowed with the credit "elevenlabs.io" in the row, but
// not for any commercial purpose, so every pack lists them (and the pack carries the list: nonCommercial).
// A file's sound name is its name without the take number (rim_01.ogg, rim_02.ogg: two takes of "rim").
'use strict';
const fs = require('fs'), path = require('path');
const repo = path.resolve(__dirname, '..', '..');
const SRC = path.join(repo, 'assets', 'audio'), OUT = path.join(repo, 'js', 'audio', 'packs');
const TYPES = { '.wav': 'audio/wav', '.ogg': 'audio/ogg', '.mp3': 'audio/mpeg', '.flac': 'audio/flac', '.m4a': 'audio/mp4' };
// (CC BY-NC, -ND and -SA are left out: no commercial use, no changes (every take is pitched), share-alike terms;
// the Pixabay Content License allows a sound's use in a game, edited, but not the download on its own)
const OK_LICENSE = /\b(CC0|public domain|CC[- ]BY(?![- ]?(NC|ND|SA))(?:[- ]\d(?:\.\d)?)?|Pixabay Content License|made by this project|generated by this project)\b/i;
// ElevenLabs' free plan (or no account): non-commercial only, with the credit
const NONCOMMERCIAL = /\bElevenLabs free plan\b.*\bnon-commercial\b/i;

function licenseRows(folder) {
  const f = path.join(SRC, folder, 'LICENSES.md');
  if (!fs.existsSync(f)) return null;
  const rows = {};
  for (const line of fs.readFileSync(f, 'utf8').split('\n')) {
    const cells = line.split('|').map((c) => c.trim()).filter((c, i, a) => i > 0 && i < a.length - 1);
    if (cells.length < 4 || /^-+$/.test(cells[0]) || /^file$/i.test(cells[0])) continue;
    rows[cells[0].replace(/`/g, '')] = { source: cells[1], author: cells[2], license: cells[3] };
  }
  return rows;
}

function pack(folder) {
  const dir = path.join(SRC, folder);
  if (!fs.existsSync(dir)) throw new Error('no folder ' + dir);
  const files = fs.readdirSync(dir).filter((f) => TYPES[path.extname(f).toLowerCase()]).sort();
  const rows = licenseRows(folder);
  if (!rows) throw new Error(folder + ': LICENSES.md is missing');
  const bad = [], nc = [];
  for (const f of files) {
    const r = rows[f];
    if (!r) bad.push(f + ': no row in LICENSES.md');
    else if (NONCOMMERCIAL.test(r.license)) {
      if (!/elevenlabs\.io|11\.ai/i.test(r.author + ' ' + r.source)) bad.push(f + ': an ElevenLabs sound needs the credit "elevenlabs.io" in its row');
      else nc.push(f);
    } else if (!OK_LICENSE.test(r.license)) bad.push(f + ': license "' + r.license + '" is not one the game can ship');
    else if (/CC[- ]BY/i.test(r.license) && !r.author) bad.push(f + ': CC BY needs the author credited');
  }
  if (bad.length) throw new Error(folder + ':\n  ' + bad.join('\n  '));
  const out = path.join(OUT, folder + '.js');
  if (!files.length) { if (fs.existsSync(out)) fs.unlinkSync(out); return { folder, files: 0, bytes: 0 }; }
  let body = '', bytes = 0;
  for (const f of files) {
    const buf = fs.readFileSync(path.join(dir, f));
    bytes += buf.length;
    body += `    ${JSON.stringify(f)}: 'data:${TYPES[path.extname(f).toLowerCase()]};base64,${buf.toString('base64')}',\n`;
  }
  const js = `/* Sound pack "${folder}": made by tools/audio/pack.js from assets/audio/${folder}/ (do not edit; licenses in\n` +
    ` * assets/audio/${folder}/LICENSES.md). ${files.length} file(s), ${bytes} bytes.` +
    (nc.length ? `\n * Not for any commercial purpose (ElevenLabs free plan, credit elevenlabs.io): ${nc.join(', ')}.` : '') + ` */\n` +
    `PBC.AudioPacks.register(${JSON.stringify(folder)}, {\n  license: 'assets/audio/${folder}/LICENSES.md',\n` +
    (nc.length ? `  nonCommercial: ${JSON.stringify(nc)},\n` : '') + `  files: {\n${body}  },\n});\n`;
  fs.mkdirSync(OUT, { recursive: true });
  fs.writeFileSync(out, js);
  return { folder, files: files.length, bytes, nc };
}

function writeIndex() {
  const have = fs.readdirSync(OUT).filter((f) => f.endsWith('.js') && f !== 'index.js').map((f) => f.slice(0, -3)).sort();
  fs.writeFileSync(path.join(OUT, 'index.js'), `/* The sound packs that exist (rewritten by tools/audio/pack.js). */\nwindow.PBC = window.PBC || {};\nPBC.AudioPacks = PBC.AudioPacks || {};\nPBC.AudioPacks.available = ${JSON.stringify(have)};\n`);
  return have;
}

const args = process.argv.slice(2);
const folders = args.includes('--all') ? fs.readdirSync(SRC).filter((f) => fs.statSync(path.join(SRC, f)).isDirectory()) : args;
if (!folders.length) { console.log('usage: node tools/audio/pack.js <folder> [...] | --all'); process.exit(1); }
let failed = false;
for (const f of folders) {
  try {
    const r = pack(f);
    console.log(`${r.folder}: ${r.files} file(s), ${r.bytes} bytes`);
    if (r.nc && r.nc.length) console.log(`  not for any commercial purpose (ElevenLabs free plan, credit elevenlabs.io): ${r.nc.join(', ')}`);
  }
  catch (e) { failed = true; console.error('pack ' + e.message); }
}
console.log('packs: ' + writeIndex().join(', '));
process.exit(failed ? 1 : 0);
